server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/catalog_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Lyy135792468
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      connection-test-query: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate   # 生产只校验
  
  cloud:
    nacos:
      discovery:
        server-addr: ${SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR:localhost:8848}
        namespace: dev
        group: COURSEHUB_GROUP
        ephemeral: true
        heartbeat-interval: 5000
        heartbeat-timeout: 15000

management:
  endpoints:
    web:
      exposure:
        include: health
