server:
  port: 8083

spring:
  application:
    name: enrollment-service
  datasource:
    url: jdbc:mysql://localhost:3306/enrollment_db?useSSL=false&serverTimezone=UTC
    username: root
    password: Lyy135792468
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# 服务地址配置
user-service:
  url: http://localhost:8081
catalog-service:
  url: http://localhost:8082